version: '3.5'
services:
  mirror-update:
    build: update
    restart: 'unless-stopped'
    volumes:
      - /volume1/docker/mirror:/mnt/mirror

  mirror-http:
    build: http
    restart: 'unless-stopped'
    volumes:
      - /volume1/docker/mirror:/mnt/mirror
    networks:
      reverse_proxy:
        ipv4_address: '172.40.0.5'
    
networks:
  reverse_proxy:
    name: reverse-proxy
    external: true
